import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, NavLink, useParams } from 'react-router-dom'
import { ArrowUpRight, GitBranch, RefreshCw, FolderTree, Layers, MessageSquare, Network, BookOpen, Route, LayoutDashboard } from 'lucide-react'
import { repositoryApi } from '../services/repositoryApi'
import type { Repository } from '../types/repository'
import SourceLinks from '../components/repository/SourceLinks'
import { ArchitectureView, FilesView, ModulesView, FlowsView, SetupView, AskView } from './RepositoryViews'
const tabs = [['overview', 'Overview', LayoutDashboard], ['architecture', 'Architecture', Network], ['modules', 'Modules', Layers], ['files', 'Files', FolderTree], ['data-flow', 'Data Flow', Route], ['setup', 'Setup', BookOpen], ['ask', 'Ask RepoMentor', MessageSquare]] as const
export default function RepositoryPage() {
  const { repositoryId = '', section = 'overview' } = useParams()
  const client = useQueryClient()
  const status = useQuery({ queryKey: ['status', repositoryId], queryFn: () => repositoryApi.status(repositoryId), refetchInterval: q => ['QUEUED', 'ANALYZING'].includes(q.state.data?.status ?? '') ? 2000 : false })
  const detail = useQuery({ queryKey: ['repository', repositoryId, status.data?.status], queryFn: () => repositoryApi.detail(repositoryId) })
  const retry = useMutation({ mutationFn: () => repositoryApi.analyze(detail.data!.url, true), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['status', repositoryId] }); await client.invalidateQueries({ queryKey: ['repository', repositoryId] }); await client.invalidateQueries({ queryKey: ['view', repositoryId] }) } })
  const error = detail.error || status.error
  if (error) return <div className="dashboard"><StateError error={error} retry={() => { void status.refetch(); void detail.refetch() }} /></div>
  if (!detail.data || !status.data) return <div className="dashboard loading" role="status">Loading repository…</div>
  const repo = detail.data, current = status.data
  return <div className="dashboard">
    <div className="breadcrumb"><Link to="/">Repositories</Link><span>/</span><span>{repo.owner} / {repo.name}</span></div>
    <header className="repository-heading"><div><p className="eyebrow">YOUR CODEBASE, EXPLAINED</p><h1>{repo.name}<span className={`status-badge ${current.status.toLowerCase()}`}>{current.status}</span></h1><p className="muted">{repo.description || `${repo.owner} / ${repo.name}`}</p><div className="repo-meta"><span><GitBranch size={14} /> {repo.default_branch ?? 'Unknown branch'}</span>{repo.commit_sha && <code>{repo.commit_sha.slice(0, 8)}</code>}<a href={repo.url} target="_blank" rel="noopener noreferrer">View on GitHub <ArrowUpRight size={14} /></a></div></div><button className="ghost-button" disabled={retry.isPending || ['QUEUED', 'ANALYZING'].includes(current.status)} onClick={() => retry.mutate()}><RefreshCw size={14} />{retry.isPending ? 'Queuing…' : 'Reanalyze'}</button></header>
    {retry.error && <p role="alert" className="error-message">{retry.error.message}</p>}
    {['QUEUED', 'ANALYZING'].includes(current.status) ? <section className="panel analysis-progress" aria-live="polite"><p className="eyebrow">GETTING TO KNOW YOUR REPOSITORY</p><h2>{current.message}</h2><p className="muted">Fetching sources, mapping structure, and preparing repository evidence.</p><progress max={100} value={current.progress} aria-label="Analysis progress" /><span>{current.progress}% complete</span><ol className="pipeline-stages">{['Fetching repository', 'Analyzing structure', 'Parsing code', 'Chunking', 'Embedding', 'Generating insights', 'Finalizing'].map(label => <li key={label} className={current.stage === label.toUpperCase().replaceAll(' ', '_') ? 'active' : ''}>{label}</li>)}</ol></section> : current.status === 'FAILED' ? <section className="panel"><h2>Analysis could not finish</h2><p role="alert" className="error-message">{current.error?.message}</p><p className="muted">Use Reanalyze to retry.</p></section> : <>
      {repo.warnings.length > 0 && <details className="notice"><summary>{repo.warnings.length} analysis {repo.warnings.length === 1 ? 'notice' : 'notices'}</summary>{repo.warnings.map((w, i) => <p key={i}>{w}</p>)}</details>}
      <nav className="dashboard-tabs" aria-label="Repository sections">{tabs.map(([path, label, Icon]) => <NavLink key={path} to={`/repositories/${repositoryId}/${path}`} className={() => section === path ? 'active' : ''}><Icon size={16} />{label}</NavLink>)}</nav>
      <div className="view-content" key={section}>{section === 'overview' ? <Overview repo={repo} /> : section === 'architecture' ? <ArchitectureView repo={repo} /> : section === 'modules' ? <ModulesView repo={repo} /> : section === 'files' ? <FilesView repo={repo} /> : section === 'data-flow' ? <FlowsView repo={repo} /> : section === 'setup' ? <SetupView repo={repo} /> : section === 'ask' ? <AskView repo={repo} /> : <p>Section not found.</p>}</div>
    </>}
  </div>
}
export function StateError({ error, retry }: {error: Error; retry: () => void}) { return <div className="panel"><p role="alert" className="error-message">{error.message}</p><button className="ghost-button" onClick={retry}>Try again</button></div> }
function Overview({ repo }: {repo: Repository}) {
  const [expanded, setExpanded] = useState(false)
  return <>
    <div className="stats-grid">{[['Files analyzed', repo.stats?.files_analyzed], ['Languages', repo.stats?.languages_detected], ['Modules', repo.stats?.modules_found], ['Code symbols', repo.stats?.symbols_found]].map(([label, value]) => <div className="stat" key={label}><strong>{value ?? '—'}</strong><span>{label}</span></div>)}</div>
    <div className="overview-grid"><section className="panel"><p className="eyebrow">THE BIG PICTURE</p><h2>Understand the project.</h2><p>{repo.summary?.purpose}</p><p className="muted">{repo.summary?.architecture_summary}</p><div className="tags">{repo.summary?.technologies.map(t => <span key={t}>{t}</span>)}</div><p className="small muted">Evidence-based structural summary</p></section><section className="panel"><p className="eyebrow">LANGUAGE COMPOSITION</p><h2>What it’s built with.</h2>{repo.languages.map(lang => <div className="language-row" key={lang.name}><div><span>{lang.name}</span><span>{lang.percentage}%</span></div><meter min={0} max={100} value={lang.percentage} aria-label={`${lang.name} share`} /></div>)}{!repo.languages.length && <p className="muted">No supported source languages detected.</p>}</section></div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">START HERE</p><h2>Your first files to read.</h2></div><Link className="text-link" to={`/repositories/${repo.repository_id}/files`}>Explore all files ↗</Link></div>{(expanded ? repo.important_files : repo.important_files.slice(0, 6)).map((file, i) => <div className="reading-row" key={file.path}><span className="reading-number">{String(i + 1).padStart(2, '0')}</span><div><SourceLinks repo={repo} sources={[{file_path: file.path, start_line: null, end_line: null, symbol: null}]} /><p className="muted small">{file.reason}</p></div><span className="tag">{file.language ?? 'Documentation / config'}</span></div>)}{!repo.important_files.length && <p className="muted">No conventional entry or dependency files were detected.</p>}{repo.important_files.length > 6 && <button className="ghost-button" onClick={() => setExpanded(!expanded)}>{expanded ? 'Show fewer' : 'Show all recommended files'}</button>}</section>
    <div className="overview-grid"><section className="panel"><p className="eyebrow">ENTRY POINTS</p><h2>Where it begins.</h2>{repo.entry_points.map(e => <div className="entry-row" key={e.file_path}><SourceLinks repo={repo} sources={[{...e, start_line: null, end_line: null}]} /><p className="small muted">{e.reason}</p></div>)}{!repo.entry_points.length && <p className="muted">No conventional entry points found.</p>}</section><section className="panel ask-invite"><MessageSquare size={24} /><h2>Follow your curiosity.</h2><p className="muted">Ask about a feature, find a function, or work out where to start. Answers come with repository sources.</p><Link className="ghost-button" to={`/repositories/${repo.repository_id}/ask`}>Ask RepoMentor ↗</Link></section></div>
  </>
}
